---
output:
  html_document:
    theme:
      version: 4
params:
  geo_uid: !r c("3520005")
  level: "csd"
# params:
#   geo_uid: !r c("6020500.02", "6020100.02")
#   level: "ct"
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE,
  out.width = "100%", fig.height = 2
)
```

```{css css-styles}
.section-heading {
  background-color: lightgrey;
  padding-left: 5px;
}

.box {
  height: 100%;
  background-color: lightgrey;
  # text-align: center;
  padding: 0.5rem;
  # margin-right: 0.5rem;
  display: flex;
  flex-direction: column;
}

.box-last {
  # margin-right: 0;
  # margin-left: 0.5rem;
}

.card-value {
  margin-top: auto;
  font-size: 2rem;
  font-weight: bold;
}
```

```{r html-utils}
section_heading <- function(title) {
  htmltools::div(
    class = "section-heading",
    htmltools::h1(title)
  )
}

subsection_heading <- function(title, class = NULL) {
  htmltools::div(
    class = "section-heading",
    htmltools::h2(title)
  )
}

snapshot_card_value <- function(value) {
  htmltools::div(
    class = "card-value",
    value
  )
}

snapshot_card <- function(title, value, ..., class = NULL) {
  htmltools::div(
    class = paste("box", class),
    htmltools::div(htmltools::HTML(title)),
    snapshot_card_value(value),
    htmltools::div(...)
  )
}

header_and_barchart <- function(header, plot) {
  shiny::column(
    width = 6,
    header,
    plot
  )
}

pull_and_format_value <- function(data, format = "percent") {
  value <- data[["value"]]

  if (is.na(value)) {
    return(htmltools::HTML("&#8212;"))
  }

  switch(format,
    percent = scales::percent(value, 0.1),
    comma = scales::comma(value, 1),
    dollar = scales::dollar(value)
  )
}
```

```{r packages}
library(dplyr)
library(censusaggregate)
library(purrr)
library(scales)
library(tidyr)
library(stringr)
library(bslib)
library(arrow)
library(censusaggregatorapp)
library(sfarrow)
library(ggplot2)
library(sf)
```

```{r data}
regions <- params$geo_uid
level <- params$level
dataset <- glue::glue("extdata/{level}_values")

data <- open_dataset(system.file(dataset, package = "censusaggregatorapp"))

vectors_data <- data %>%
  filter(geo_uid %in% regions) %>%
  select(-id) %>%
  collect()

vectors_data <- vectors_data %>%
  mutate(geo_uid = forcats::fct_expand(geo_uid, regions))

metadata <- switch(level,
  "csd" = csd,
  "ct" = ct
) %>%
  filter(geo_uid %in% regions)

vectors_data <- vectors_data %>%
  # tidyr::complete(vector, geo_uid, fill = list(value = 0)) %>%
  left_join(metadata, by = "geo_uid")

# Collapse / fake metadata for age cohorts

age_cohorts_update <- tidyr::crossing(vector = c("0 to 14", "15 to 24", "25 to 44", "45 to 65", "65 to 84", "85+"), geo_uid = regions) %>%
  mutate(
    highest_parent_vector = "v_CA16_1",
    units = "Number",
    aggregation = "Additive",
    vector_label_short = "age_cohorts",
    label = vector
  ) %>%
  left_join(vectors_data %>% select(geo_uid, vector, value), by = c("vector", "geo_uid"))

vectors_data <- vectors_data %>%
  left_join(censusaggregatorapp::vectors, by = "vector") %>%
  anti_join(age_cohorts_update, by = c("vector", "geo_uid"))

vectors_data <- vectors_data %>%
  bind_rows(age_cohorts_update)

vectors_data <- vectors_data %>%
  derive_aggregation_type()

vectors_metadata <- censusaggregatorapp::vectors %>%
  bind_rows(
    age_cohorts_update %>%
      select(-geo_uid, -value) %>%
      distinct()
  )

# Aggregate vectors - treat v_CA16_407 (land area) separately, since it will be used for population density, and v_CA16_402 (population 2011) separately, since it will be used for population change

vectors_data_filtered <- vectors_data %>%
  filter(!(vector %in% c("v_CA16_407", "v_CA16_402")))

data_breakdown <- vectors_data_filtered %>%
  aggregate_census_vectors() %>%
  distinct() %>%
  left_join(vectors_metadata, by = c("highest_parent_vector", "vector", "type", "label", "units", "parent_vector", "aggregation", "details")) %>%
  select(highest_parent_vector, vector, label, vector_label_short, value, value_proportion) %>%
  group_by(highest_parent_vector) %>%
  tidyr::fill(vector_label_short, .direction = "updown") %>%
  ungroup()
```

```{r map, fig.height = 5, dpi = 300}
boundaries_dataset <- glue::glue("extdata/{level}")

boundaries_data <- open_dataset(system.file(boundaries_dataset, package = "censusaggregatorapp"))
boundaries_data <- boundaries_data %>%
  filter(geo_uid %in% regions) %>%
  read_sf_dataset()

boundaries_data %>%
  st_union() %>%
  ggplot() +
  geom_sf(fill = NA) +
  theme_void()
```


```{r snapshot_heading}
section_heading("Snapshot")
```

::: {.row .mb-2}

```{r snapshot}
# Number of geographies (CSDs/CTs), population, number of households, population change (2011 to 2016), population density

areas_selected <- glue::glue("{n} {geography}{s}",
  n = length(unlist(regions)),
  geography = case_when(
    level == "CSD" ~ "Census subdivision",
    level == "CT" ~ "Census tract"
  ),
  s = ifelse(n > 1, "s", "")
)

population <- data_breakdown %>%
  filter(vector_label_short == "population_2016") %>%
  pull_and_format_value("comma")

households <- metadata %>%
  select(geo_uid, households) %>%
  distinct() %>%
  summarise(value = sum(households)) %>%
  pull_and_format_value("comma")

population_change <- vectors_data %>%
  aggregate_population_change() %>%
  pull_and_format_value()

population_density <- vectors_data %>%
  filter(label %in% c("Population, 2016", "Land area in square kilometres")) %>%
  aggregate_population_density() %>%
  pull_and_format_value("comma")
```

```{r population}
shiny::column(
  width = 3,
  snapshot_card("Population", population)
)
```

```{r population_change}
shiny::column(
  width = 3,
  snapshot_card("Population change<br>(2011 to 2016)", population_change)
)
```

```{r population_density}
shiny::column(
  width = 3,
  snapshot_card("Population density<br>(people per square km)", population_density)
)
```

```{r households}
shiny::column(
  width = 3,
  snapshot_card("Households", households)
)
```

:::

::: {.row}

```{r age-cohorts, out.height = 1}
age_cohorts <- data_breakdown %>%
  filter(
    vector_label_short == "age_cohorts",
    vector != highest_parent_vector
  ) %>%
  mutate(label = forcats::fct_reorder(label, label))

header_and_barchart(
  subsection_heading("Population by age cohorts"),
  age_cohorts %>%
    inline_barchart()
)
```

:::

```{r section-households-families-education-language}
section_heading("Households, families, education, and language")
```

::: {.row}

```{r household_size}
household_size <- data_breakdown %>%
  filter(
    vector_label_short == "household_size",
    vector != highest_parent_vector
  ) %>%
  mutate(label = ifelse(label == "5 or more persons", "5+ persons", label)) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Private households by size"),
  household_size %>%
    inline_barchart()
)
```

```{r family_type}
family_type <- data_breakdown %>%
  filter(
    vector_label_short == "family_type",
    vector != highest_parent_vector
  ) %>%
  # mutate(label = recode("Total couple families" = "")
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Family type"),
  family_type %>%
    inline_barchart()
)
```

```{r household_type}
multiple_family_households <- data_breakdown %>%
  filter(
    vector_label_short == "household_type",
    vector != highest_parent_vector
  ) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Multiple family households"),
  multiple_family_households %>%
    inline_barchart()
)
```

```{r educational_attainment}
educational_attainment <- data_breakdown %>%
  filter(
    vector_label_short == "educational_attainment",
    vector != highest_parent_vector
  ) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Educational attainment"),
  educational_attainment %>%
    inline_barchart()
)
```

```{r knowledge_of_english}
knowledge_of_english <- data_breakdown %>%
  filter(
    vector_label_short == "knowledge_of_english",
    vector != highest_parent_vector
  ) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Knowledge of English"),
  knowledge_of_english %>%
    inline_barchart()
)
```

```{r language_at_home}
language_at_home <- data_breakdown %>%
  filter(vector_label_short == "top_10_languages") %>%
  filter(vector != highest_parent_vector) %>%
  top_n(10, wt = value) %>%
  arrange(-value) %>%
  derive_census_vector_order(by_value = TRUE)

header_and_barchart(
  subsection_heading("Language spoken at home"),
  language_at_home %>%
    inline_barchart()
)
```

:::

```{r section-income-housing}
section_heading("Income and housing")
```

::: {.row .mb-2}

```{r median_income}
shiny::column(
  width = 4,
  snapshot_card("Estimated median income", "---")
)
```

```{r lim_at}
lim_at <- data_breakdown %>%
  filter(vector_label_short == "lim_at") %>%
  select(-value, value = value_proportion) %>%
  pull_and_format_value()

shiny::column(
  width = 4,
  snapshot_card("Low income (LIM-AT)", lim_at)
)
```

```{r unaffordable_housing}
unaffordable_housing <- data_breakdown %>%
  filter(
    vector_label_short == "unaffordable_housing",
    vector != highest_parent_vector
  ) %>%
  select(-value, value = value_proportion) %>%
  pull_and_format_value()

shiny::column(
  width = 4,
  snapshot_card("Unaffordable housing", unaffordable_housing)
)
```

:::

::: {.row}

```{r shelter-cost}
shelter_cost <- data_breakdown %>%
  filter(
    str_starts(vector_label_short, "shelter_cost"),
    vector != highest_parent_vector
  ) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Average shelter cost"),
  shelter_cost %>%
    inline_barchart("dollar")
)
```


```{r household-tenure}
household_tenure <- data_breakdown %>%
  filter(
    vector_label_short == "household_tenure",
    vector != highest_parent_vector
  ) %>%
  derive_census_vector_order()

header_and_barchart(
  subsection_heading("Household tenure"),
  household_tenure %>%
    inline_barchart()
)
```

:::

```{r section-diversity-immigration}
section_heading("Diversity and immigration")
```

::: {.row .mb-2}

```{r visible-minority-summary}
visible_minority <- data_breakdown %>%
  filter(
    vector_label_short == "visible_minority",
    vector != highest_parent_vector
  )

visible_minority_summary <- visible_minority %>%
  filter(label == "Total visible minority population") %>%
  select(-value, value = value_proportion) %>%
  pull_and_format_value()

shiny::column(
  width = 3,
  snapshot_card("Visible minority", visible_minority_summary)
)
```

```{r immigrant-status}
immigrant_status <- data_breakdown %>%
  filter(
    vector_label_short == "immigrant_status",
    vector != highest_parent_vector
  ) %>%
  select(-value) %>%
  rename(value = value_proportion)

immigrant_status_total <- immigrant_status %>%
  filter(label == "Immigrants") %>%
  pull_and_format_value()

immigrant_status_recent <- immigrant_status %>%
  filter(label != "Immigrants") %>%
  pull_and_format_value()

shiny::column(
  width = 3,
  snapshot_card("Total immigrants", immigrant_status_total)
)

shiny::column(
  width = 3,
  snapshot_card("Recent immigrants<br>(2011 to 2016)", immigrant_status_recent)
)
```

```{r aboriginal-identity}
aboriginal_identity <- data_breakdown %>%
  filter(
    vector_label_short == "aboriginal_identity",
    vector != highest_parent_vector
  ) %>%
  select(-value, value = value_proportion) %>%
  pull_and_format_value()

shiny::column(
  width = 3,
  snapshot_card("Aboriginal identity", aboriginal_identity)
)
```

:::

::: {.row}

```{r visible-minority-breakdown}
visible_minority <- data_breakdown %>%
  filter(
    vector_label_short == "visible_minority",
    vector != highest_parent_vector
  ) %>%
  filter(!label %in% c("Total visible minority population", "Not a visible minority")) %>%
  derive_census_vector_order(TRUE)

header_and_barchart(
  subsection_heading("Visible minority population"),
  visible_minority %>%
    inline_barchart()
)
```

```{r ethnic_origin}
ethnic_origin <- data_breakdown %>%
  filter(vector_label_short == "ethnic_origin") %>%
  filter(vector != highest_parent_vector) %>%
  top_n(10, wt = value) %>%
  arrange(-value) %>%
  derive_census_vector_order(by_value = TRUE)

header_and_barchart(
  subsection_heading("Country of origin"),
  ethnic_origin %>%
    inline_barchart()
)
```

:::
